---
title: "summary-figures"
format: html
editor: visual
---

## Packages, Package version control, directories

```{r Setup}
library("groundhog")
# list additional packages in vector below
pkgs <- c(
  "readr",
  "tidyverse", 
  "magrittr",
  "readxl") 
# Keep this date set to load in version controlled packages
groundhog.library(pkgs, "2023-01-01")

## Set up directories 
if(dir.exists(file.path("../figures"))){
  fig_dir <- file.path("../figures")
} else{dir.create(file.path("../figures"))
  fig_dir <- file.path("../figures")
}

if(dir.exists(file.path("../data"))){
  data_dir <- file.path("../data")
} else{dir.create(file.path("../data"))
  data_dir <- file.path("../data")
}
```

## Read in Data

```{r Import_Data}
## Compiled vessel data
comp_vessels <- read_csv(file.path(data_dir,"CompiledVesselsIndicators-2023-01-26.csv"))

## IUU Vessel List
iuu_vessels <- read_excel(file.path(data_dir,"IUUList-20230127.xls"), sheet = "IUUList")

## Set company variable (change based on which report is being generated)
company <- "NESI"
sup_chain <- "Sri Lanka Yellowfin"

## Filter data by company & supply chain
vessels <- comp_vessels %>% 
  filter(c == company,
         c_listname == sup_chain)
```

```{r iuu_vessel_list}

iuu_listed <- iuu_vessels %>% 
  filter(CurrentlyListed == "True") %>% 
  select(Name, MMSI, VesselStatus, 20:47)

iuu_listed$MMSI <- as.numeric(iuu_listed$MMSI)

scrt_vessels <- vessels %>% 
  select(c_name, gfw_mmsi) %>% 
  filter(gfw_mmsi > 0) %>% 
  rename("Name" = c_name,
         "MMSI" = gfw_mmsi)

# cross validate IUU list and scrt vessels by name and mmsi
iuu_mmsi <- iuu_listed %>%
  inner_join(scrt_vessels, by = c("MMSI"))
iuu_name <- iuu_listed %>% 
  inner_join(scrt_vessels, by = "Name")

# No vessels match either on name or MMSI
```


```{r key_data_elements}

#### mmsi
mmsi <- vessels %>% 
  select(c_mmsi) %>% 
  filter(c_mmsi > 0)

# % of vessels with mmsi 
nrow(mmsi) / nrow(vessels)

# gfw mmsi found
mmsi_gfw <- vessels %>% 
  select(gfw_mmsi) %>% 
  filter(gfw_mmsi > 0)

nrow(mmsi_gfw) / nrow(vessels)

##### AIS disabled

ais_dis <- vessels %>% 
  select(gfw_prop_ais_disable) %>% 
  filter(gfw_prop_ais_disable > 0)
  
nrow(ais_dis)

##### AIS availability
ais_avl <- vessels %>% 
  select(m_AIS, gfw_prop_ais_coverage) %>% 
  filter(m_AIS == "Have AIS for this vessel")

# percent vessels with AIS
nrow(ais_avl) / nrow(vessels)

ais_gfw <- vessels %>% 
  select(m_AIS, gfw_prop_ais_coverage) %>% 
  drop_na()

# percent vessels picked up by GFW
nrow(ais_gfw) / nrow(vessels)

# percent with AIS coverage
ais_cover <- vessels %>% 
  select(gfw_prop_ais_coverage) %>%
  filter(gfw_prop_ais_coverage > 0)
# percent of all vessels 
nrow(ais_cover) / nrow(vessels)

range(ais_cover)

###### Port Matching 
port_match <- vessels %>% 
  select(port_matching) %>% 
  na.omit() %>% 
  filter(!port_matching %in% c("No AIS coverage", "AIS turned off before port entry"))

nrow(port_match) / nrow(vessels)


```


```{r function_doughnut}
make_doughnut <- function(indicator) {
  fig_data <- indicator %>%
    select(data_vessels, nodata_vessels) %>%
    pivot_longer(
      cols = c(data_vessels, nodata_vessels),
      names_to = "data",
      values_to = "count"
    ) %>%
    mutate(fraction = count / sum(count))
  fig_data$ymax = cumsum(fig_data$fraction)
  fig_data$ymin <- c(0, head(fig_data$ymax, n = -1))
  
  
  # doughnut color
  
  dough_color <- c("#0074DD", "#9BCCFD")
  
  # doughnut figure
  doughnut <- ggplot(fig_data,
                     aes(
                       ymax = ymax,
                       ymin = ymin,
                       xmax = 4,
                       xmin = 3,
                       fill = data
                     )) +
    geom_rect() +
    # Try to remove that to understand how the chart is built initially
    coord_polar(theta = "y") +
    # adjust thickness
    xlim(c(0, 4)) +
    theme_void() +
    scale_fill_manual(values = dough_color) +
    #scale_color_manual(values = dough_color) +
    theme(legend.position = "none")
  
  ggsave(doughnut,
         filename = file.path(fig_dir,
                              paste0("doughnut_", 
                                     deparse(substitute(indicator)), 
                                     ".png")),
           width = 0.5,
           height = 0.5,
           units = "in",
           dpi = 600
         )
}

# calc percent vessels with data
calc_prt_vessels <- function(indicator){
  indicator$data_vessels/(indicator$data_vessels + indicator$nodata_vessels)
}


```


## High Priority

```{r High_priority}
#### IUU Listed Vessels

#### Unauthorized Fishing in RFMO

#### MPA Fishing hours 

mpa_hr <- vessels %>% 
  select(gfw_fishing_hr_mpa) %>% 
  summarize("data_vessels" = length(vessels$gfw_fishing_hr_mpa[which(!is.na(vessels$gfw_fishing_hr_mpa))]),
            "nodata_vessels" = length(vessels$gfw_fishing_hr_mpa[which(is.na(vessels$gfw_fishing_hr_mpa))]),
           "mpa_vessels" = length(vessels$gfw_fishing_hr_mpa[which(vessels$gfw_fishing_hr_mpa > 0)]),
           "mpa_hrs" = sum(gfw_fishing_hr_mpa, na.rm = T)
           )
# make vessel data availability doughnut figure
make_doughnut(mpa_hr)

# vessels with data
calc_prt_vessels(mpa_hr)

#### Unauthorized Transshipment

un_tship <- vessels %>% 
  select(gfw_n_transship_unauthorized) %>% 
  summarize("data_vessels" = length(vessels$gfw_n_transship_unauthorized[which(!is.na(vessels$gfw_n_transship_unauthorized))]),
            "nodata_vessels" = length(vessels$gfw_n_transship_unauthorized[which(is.na(vessels$gfw_n_transship_unauthorized))]),
            "n_unauth" = sum(gfw_n_transship_unauthorized, na.rm = T)
            )
make_doughnut(un_tship)
calc_prt_vessels(un_tship)
```

## Medium Priority

```{r}
## Vessel Name Changes 

## Vessel Flag Changes 

## Intentional AIS Disabling
ais_dis <- vessels %>% 
  select(gfw_prop_ais_disable) %>% 
  summarize("data_vessels" = length(vessels$gfw_prop_ais_disable[which(!is.na(vessels$gfw_prop_ais_disable))]),
            "nodata_vessels" = length(vessels$gfw_prop_ais_disable[which(is.na(vessels$gfw_prop_ais_disable))]),
            "n_vessels_dis" = length(vessels$gfw_prop_ais_disable[which(vessels$gfw_prop_ais_disable > 0)])
            )

make_doughnut(ais_dis)
calc_prt_vessels(ais_dis)

## Long Fishing Trips

long_trip <- vessels %>% 
  select(gfw_n_long_trips) %>% 
  summarize("data_vessels" = length(vessels$gfw_n_long_trips[which(!is.na(vessels$gfw_n_long_trips))]),
            "nodata_vessels" = length(vessels$gfw_n_long_trips[which(is.na(vessels$gfw_n_long_trips))]),
            "n_longtrip" = sum(gfw_n_long_trips, na.rm = T))

make_doughnut(long_trip)
calc_prt_vessels(long_trip)
```

## Low Priority

```{r}
## EU Carding Status 
card_eu <- vessels %>% 
  select(m_c_eu_flag) 

unique(card_eu)

## US Carding Status
card_us <- vessels %>% 
  select(m_c_us_flag) 

unique(card_us)

## IUU Species Risk

iuu_species <- vessels %>% 
  select(m_petro_score)

unique(iuu_species)
```

